//
//  WALIcons.h
//  wallabag for iOS
//
//  Created by (null) on 26.07.14.
//  Copyright (c) 2014 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface WALIcons : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolbarUnreadTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolbarReadTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolbarChangeThemeTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolbarActionsTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* navbarListTargets;

// Colors
+ (UIColor*)tintColor;

// Generated Images
+ (UIImage*)imageOfToolbarUnread;
+ (UIImage*)imageOfToolbarRead;
+ (UIImage*)imageOfToolbarChangeTheme;
+ (UIImage*)imageOfToolbarActions;
+ (UIImage*)imageOfNavbarList;

@end
