//
//  WallabagIcons.h
//  wallabag for iOS
//
//  Created by (null) on 26.07.14.
//  Copyright (c) 2014 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface WallabagIcons : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolbarUnreadTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolbarReadTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* changeThemeTargets;

// Colors
+ (UIColor*)tintColor;

// Generated Images
+ (UIImage*)imageOfToolbarUnreadWithFrame: (CGRect)frame;
+ (UIImage*)imageOfToolbarReadWithFrame: (CGRect)frame;
+ (UIImage*)imageOfChangeThemeWithFrame: (CGRect)frame;

@end
