//
//  NSString+HashesTests.m
//  Wallabag
//
//  Created by Kevin Meyer on 10/02/15.
//  Copyright (c) 2015 Wallabag. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <XCTest/XCTest.h>
#import "NSString+Hashes.h"

@interface NSString_HashesTests : XCTestCase

@end

@implementation NSString_HashesTests

- (void)setUp {
    [super setUp];
    // Put setup code here. This method is called before the invocation of each test method in the class.
}

- (void)tearDown {
    // Put teardown code here. This method is called after the invocation of each test method in the class.
    [super tearDown];
}

- (void)testBase64Encoding1 {
	NSString *clear = @"small test 1337!%D";
	NSString *base64 = @"c21hbGwgdGVzdCAxMzM3ISVE"; // Generated by https://www.base64encode.org/

	XCTAssertEqualObjects([clear stringByEncodingBase64], base64);
	XCTAssertEqualObjects([base64 stringByDecodingBase64], clear);
}

- (void)testBase64Encoding2 {
	NSString *clear = @"lorem ipsum dolor sit amet";
	NSString *base64 = @"bG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQ="; // Generated by https://www.base64encode.org/
	
	XCTAssertEqualObjects([clear stringByEncodingBase64], base64);
	XCTAssertEqualObjects([base64 stringByDecodingBase64], clear);
}

- (void)testBase64Encoding3 {
	NSString *clear = @"The terms foobar (/ˈfuːbɑr/), fubar, or foo, bar, baz and qux (alternatively, quux) and sometimes norf[1] are sometimes used as placeholder names (also referred to as metasyntactic variables) in computer programming or computer-related documentation.";
	NSString *base64 = @"VGhlIHRlcm1zIGZvb2JhciAoL8uIZnXLkGLJkXIvKSwgZnViYXIsIG9yIGZvbywgYmFyLCBiYXogYW5kIHF1eCAoYWx0ZXJuYXRpdmVseSwgcXV1eCkgYW5kIHNvbWV0aW1lcyBub3JmWzFdIGFyZSBzb21ldGltZXMgdXNlZCBhcyBwbGFjZWhvbGRlciBuYW1lcyAoYWxzbyByZWZlcnJlZCB0byBhcyBtZXRhc3ludGFjdGljIHZhcmlhYmxlcykgaW4gY29tcHV0ZXIgcHJvZ3JhbW1pbmcgb3IgY29tcHV0ZXItcmVsYXRlZCBkb2N1bWVudGF0aW9uLg=="; // Generated by https://www.base64encode.org/
	
	XCTAssertEqualObjects([clear stringByEncodingBase64], base64);
	XCTAssertEqualObjects([base64 stringByDecodingBase64], clear);
}

@end
