//
//  WALUserTests.m
//  Wallabag
//
//  Created by Kevin Meyer on 10/02/15.
//  Copyright (c) 2015 Wallabag. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <XCTest/XCTest.h>

#import "WALUser.h"
#import "NSString+Hashes.h"

@interface WALUserTests : XCTestCase

@end

@implementation WALUserTests

- (void)setUp {
    [super setUp];
    // Put setup code here. This method is called before the invocation of each test method in the class.
}

- (void)tearDown {
    // Put teardown code here. This method is called after the invocation of each test method in the class.
    [super tearDown];
}

- (void)testWSSE1 {
	NSString *username = @"wallabag";
	NSString *password = @"02b92862ab03de17e217ee5fa53fbf52eed039ca"; // "wallabag" hashed and salted

	WALUser *user = [[WALUser alloc] initWithUsername:username andHashedPassword:password];
	NSString *headerValue = [user wsseHeaderValue];
	
	NSLog(@"Header Value:\n%@", headerValue);
	XCTAssertNotNil(headerValue);
}

- (void)testWSSEExampleInput1 {
	NSString *username = @"wallabag";
	NSString *password = @"02b92862ab03de17e217ee5fa53fbf52eed039ca"; // "wallabag" hashed and salted
	
	NSString *nonce = @"2bfe7c14fd225564";
	NSString *timestamp = @"2015-02-10T18:13:41Z";
	
	NSString *expectedValue = @"UsernameToken Username=\"wallabag\", PasswordDigest=\"co+gfpXt6KRC1ol2SgGhqn9SNsU=\", Nonce=\"MmJmZTdjMTRmZDIyNTU2NA==\", Created=\"2015-02-10T18:13:41Z\""; // Generated by http://www.teria.com/~koseki/tools/wssegen/
	
	WALUser *user = [[WALUser alloc] initWithUsername:username andHashedPassword:password];
	[user generateWSSEWithNonce:nonce andTimestamp:timestamp];
	NSString *headerValue = [user wsseHeaderValue];
	
	//NSLog(@"Header Value:\n%@", headerValue);
	XCTAssertNotNil(headerValue);
	XCTAssertEqualObjects(expectedValue, headerValue);
}

- (void)testWSSEExampleInput2 {
	NSString *username = @"wallabag";
	NSString *password = @"02b92862ab03de17e217ee5fa53fbf52eed039ca"; // "wallabag" hashed and salted
	
	NSString *nonce = @"69476B47-79F1-4B2A-B3DB-7F633D01E6DD";
	NSString *timestamp = @"2015-02-10T18:25:49Z";
	
	NSString *expectedValue = @"UsernameToken Username=\"wallabag\", PasswordDigest=\"opbOHmZjAUEZtwlHeaGYOd8T++4=\", Nonce=\"Njk0NzZCNDctNzlGMS00QjJBLUIzREItN0Y2MzNEMDFFNkRE\", Created=\"2015-02-10T18:25:49Z\""; // Generated by http://www.teria.com/~koseki/tools/wssegen/
	
	WALUser *user = [[WALUser alloc] initWithUsername:username andHashedPassword:password];
	[user generateWSSEWithNonce:nonce andTimestamp:timestamp];
	NSString *headerValue = [user wsseHeaderValue];
	
	//NSLog(@"Header Value:\n%@", headerValue);
	XCTAssertNotNil(headerValue);
	XCTAssertEqualObjects(expectedValue, headerValue);
}


- (void)testWSSEGenerateFunction {
	NSString *username = @"wallabag";
	NSString *password = @"02b92862ab03de17e217ee5fa53fbf52eed039ca"; // "wallabag" hashed and salted
	
	WALUser *user = [[WALUser alloc] initWithUsername:username andHashedPassword:password];
	NSString *headerValue1 = [user wsseHeaderValue];
	NSString *headerValue2 = [user wsseHeaderValue];
	
	XCTAssertEqualObjects(headerValue1, headerValue2);
	
	[user generateWSSE];
	NSString *headerValue3 = [user wsseHeaderValue];
	XCTAssertNotEqualObjects(headerValue1, headerValue3);
}

- (void)testWSSEGenerateWithValuesFunction {
	NSString *username = @"wallabag";
	NSString *password = @"02b92862ab03de17e217ee5fa53fbf52eed039ca"; // "wallabag" hashed and salted
	
	NSString *nonce = @"69476B47-79F1-4B2A-B3DB-7F633D01E6DD";
	NSString *timestamp = @"2015-02-10T18:25:49Z";
	
	NSString *expectedValue = @"UsernameToken Username=\"wallabag\", PasswordDigest=\"opbOHmZjAUEZtwlHeaGYOd8T++4=\", Nonce=\"Njk0NzZCNDctNzlGMS00QjJBLUIzREItN0Y2MzNEMDFFNkRE\", Created=\"2015-02-10T18:25:49Z\""; // Generated by http://www.teria.com/~koseki/tools/wssegen/

	WALUser *user = [[WALUser alloc] initWithUsername:username andHashedPassword:password];
	[user generateWSSEWithNonce:nonce andTimestamp:timestamp];
	NSString *headerValue1 = [user wsseHeaderValue];
	NSString *headerValue2 = [user wsseHeaderValue];
	
	XCTAssertEqualObjects(headerValue1, headerValue2);
	XCTAssertEqualObjects(headerValue1, expectedValue);
	
	[user generateWSSE];
	NSString *headerValue3 = [user wsseHeaderValue];
	XCTAssertNotEqualObjects(headerValue1, headerValue3);

}

- (void)testWSSEGenerateWithValuesAndTimestampIsNil {
	NSString *username = @"wallabag";
	NSString *password = @"02b92862ab03de17e217ee5fa53fbf52eed039ca"; // "wallabag" hashed and salted
	
	NSString *nonce = nil;
	NSString *timestamp = @"2015-02-10T18:25:49Z";
	
	WALUser *user = [[WALUser alloc] initWithUsername:username andHashedPassword:password];
	[user generateWSSEWithNonce:nonce andTimestamp:timestamp];
	NSString *headerValue1 = [user wsseHeaderValue];
	NSString *headerValue2 = [user wsseHeaderValue];
	
	XCTAssertNotNil(headerValue1);
	XCTAssertEqualObjects(headerValue1, headerValue2);
	
	XCTAssert([headerValue1 containsString:timestamp]);
	XCTAssertFalse([headerValue1 containsString:@"(null)"]);
}

- (void)testWSSEGenerateWithValuesAndNonceIsNil {
	NSString *username = @"wallabag";
	NSString *password = @"02b92862ab03de17e217ee5fa53fbf52eed039ca"; // "wallabag" hashed and salted
	
	NSString *nonce = @"69476B47-79F1-4B2A-B3DB-7F633D01E6DD";
	NSString *timestamp = nil;
	
	WALUser *user = [[WALUser alloc] initWithUsername:username andHashedPassword:password];
	[user generateWSSEWithNonce:nonce andTimestamp:timestamp];
	NSString *headerValue1 = [user wsseHeaderValue];
	NSString *headerValue2 = [user wsseHeaderValue];
	
	XCTAssertNotNil(headerValue1);
	XCTAssertEqualObjects(headerValue1, headerValue2);
	
	XCTAssert([headerValue1 containsString:[nonce stringByEncodingBase64]]);
	XCTAssertFalse([headerValue1 containsString:@"(null)"]);
}

- (void)testWSSEHeaderKey {
	WALUser *user = [[WALUser alloc] init];
	
	XCTAssertNotNil([user wsseHeaderKey]);
	XCTAssertEqualObjects(@"X-WSSE", [user wsseHeaderKey]);
}

- (void)testPasswordHashing {
	WALUser *user = [[WALUser alloc] init];
	NSString *username = @"wallabag";
	NSString *password = @"wallabag";
	NSString *salt = @"a7bdce59b6077a014d22c6f749e681f7";
	NSString *expected = @"49e5b5e8469bc313f78df0640a61d374dea8e4d8";
	
	user.username = username;
	[user setPassword:password withSalt:salt];
	
	XCTAssertNotNil(user.passwordHashed);
	XCTAssertEqualObjects(user.passwordHashed, expected);
}

@end
