//
//  WALUserTests.m
//  Wallabag
//
//  Created by Kevin Meyer on 10/02/15.
//  Copyright (c) 2015 Wallabag. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <XCTest/XCTest.h>
#import "WALUser.h"

@interface WALUserTests : XCTestCase

@end

@implementation WALUserTests

- (void)setUp {
    [super setUp];
    // Put setup code here. This method is called before the invocation of each test method in the class.
}

- (void)tearDown {
    // Put teardown code here. This method is called after the invocation of each test method in the class.
    [super tearDown];
}

- (void)testWSSE1 {
	NSString *username = @"wallabag";
	NSString *password = @"02b92862ab03de17e217ee5fa53fbf52eed039ca"; // "wallabag" hashed and salted

	WALUser *user = [[WALUser alloc] initWithUsername:username andHashedPassword:password];
	NSString *headerValue = [user wsseHeaderValue];
	
	NSLog(@"Header Value:\n%@", headerValue);
	XCTAssertNotNil(headerValue);
}

- (void)testWSSEExampleInput {
	NSString *username = @"wallabag";
	NSString *password = @"02b92862ab03de17e217ee5fa53fbf52eed039ca"; // "wallabag" hashed and salted
	
	NSString *nonce = @"2bfe7c14fd225564";
	NSString *timestamp = @"2015-02-10T18:13:41Z";
	
	NSString *expectedValue = @"UsernameToken Username=\"wallabag\", PasswordDigest=\"co+gfpXt6KRC1ol2SgGhqn9SNsU=\", Nonce=\"MmJmZTdjMTRmZDIyNTU2NA==\", Created=\"2015-02-10T18:13:41Z\""; // Generated by http://www.teria.com/~koseki/tools/wssegen/
	
	WALUser *user = [[WALUser alloc] initWithUsername:username andHashedPassword:password];
	[user generateWSSEWithNonce:nonce andTimestamp:timestamp];
	NSString *headerValue = [user wsseHeaderValue];
	
	//NSLog(@"Header Value:\n%@", headerValue);
	XCTAssertNotNil(headerValue);
	XCTAssertEqualObjects(expectedValue, headerValue);
}

- (void)testWSSEGenerateFunction {
	NSString *username = @"wallabag";
	NSString *password = @"02b92862ab03de17e217ee5fa53fbf52eed039ca"; // "wallabag" hashed and salted
	
	WALUser *user = [[WALUser alloc] initWithUsername:username andHashedPassword:password];
	NSString *headerValue1 = [user wsseHeaderValue];
	NSString *headerValue2 = [user wsseHeaderValue];
	
	XCTAssertEqualObjects(headerValue1, headerValue2);
	
	[user generateWSSE];
	NSString *headerValue3 = [user wsseHeaderValue];
	XCTAssertNotEqualObjects(headerValue1, headerValue3);
}

- (void)testWSSEHeaderKey {
	WALUser *user = [[WALUser alloc] init];
	
	XCTAssertNotNil([user wsseHeaderKey]);
	XCTAssertEqualObjects(@"X-WSSE", [user wsseHeaderKey]);
}

@end
